### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by ap-atul** [actondev/wavelet-denoiser#3]
When the audio file is 10 min +, my PC with 8GB of RAM runs out of memory. How can I process the audio using some chunks system, to reduce the memory usage?

**Comment by actondev** [comment]
Hi @AP-Atul .
Unfortunately this is a known issue (haven't stumbled upon this but knew it would happen), since the denoising is implemented in an "offline" mode (parsing everything first).

The chunks processing, as you said, should be implemented for large files like in your case. Unfortunately at the moment I'm not up to implementing this.

Though, in case you feel like taking a shot at implementing it yourself some notes:
The tricky thing would be about calculating the "noise" profile. What's done at the moment, is parsing the whole file to find the average loudness level and "guess" the silence aka the noise profile.
Now, the noise is one continuous region in your sound. Since your file is 10 minutes, I guess that noise profile could be something that is changing. So not sure if this tool is fitting your usecase.

Let me know your thoughts on this. Also, I'm interested how you stumbled upon this repo and also if you tried other options.

**Comment by ap-atul** [comment]
Previously I used FFT to reduce noise. Later found out wavelet can do it faster. So searched and found your repo. It does really good job, when I tried on small files.
My approach:-
The noise profiler works good. Only for denoising, I tried using the blocks read of soundfile lib. The blocks does get cleaned but has to save separately and then combine all wav files. 
Also I dont understand your code fully. 

Currently I am using basic things from pywt and calculating the threshold using mean sqrt
